const defaultObject = {
	"objectID": 398376,
	"isHighlight": false,
	"accessionNumber": "43.33.1136",
	"accessionYear": "1943",
	"isPublicDomain": true,
	"primaryImage": "https://images.metmuseum.org/CRDImages/dp/original/DP-21499-001.jpg",
	"primaryImageSmall": "https://images.metmuseum.org/CRDImages/dp/web-large/DP-21499-001.jpg",
	"additionalImages": [],
	"constituents": [
		{
			"constituentID": 104183,
			"role": "Artist",
			"name": "Joseph Vogel",
			"constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500336487",
			"constituentWikidata_URL": "https://www.wikidata.org/wiki/Q99361077",
			"gender": ""
		},
		{
			"constituentID": 163465,
			"role": "Publisher",
			"name": "WPA",
			"constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500227524",
			"constituentWikidata_URL": "https://www.wikidata.org/wiki/Q1200079",
			"gender": ""
		}
	],
	"department": "Drawings and Prints",
	"objectName": "Print",
	"title": "Vision",
	"culture": "",
	"period": "",
	"dynasty": "",
	"reign": "",
	"portfolio": "",
	"artistRole": "Artist",
	"artistPrefix": "",
	"artistDisplayName": "Joseph Vogel",
	"artistDisplayBio": "American, 1911–1995",
	"artistSuffix": "",
	"artistAlphaSort": "Vogel, Joseph",
	"artistNationality": "American",
	"artistBeginDate": "1911",
	"artistEndDate": "1995",
	"artistGender": "",
	"artistWikidata_URL": "https://www.wikidata.org/wiki/Q99361077",
	"artistULAN_URL": "http://vocab.getty.edu/page/ulan/500336487",
	"objectDate": "1939",
	"objectBeginDate": 1939,
	"objectEndDate": 1939,
	"medium": "Lithograph",
	"dimensions": "sheet: 14 5/8 x 20 1/2 in. (37.2 x 52 cm)",
	"measurements": [{
		"elementName": "Sheet",
		"elementDescription": null,
		"elementMeasurements": {
			"Height": 37.2,
			"Width": 52
		}
	}],
	"creditLine": "Gift of the Work Projects Administration, New York, 1943",
	"geographyType": "",
	"city": "",
	"state": "",
	"county": "",
	"country": "",
	"region": "",
	"subregion": "",
	"locale": "",
	"locus": "",
	"excavation": "",
	"river": "",
	"classification": "Prints",
	"rightsAndReproduction": "",
	"linkResource": "",
	"metadataDate": "2021-08-03T04:39:47.55Z",
	"repository": "Metropolitan Museum of Art, New York, NY",
	"objectURL": "https://www.metmuseum.org/art/collection/search/398376",
	"tags": null,
	"objectWikidata_URL": "",
	"isTimelineWork": false,
	"GalleryNumber": "690"
};

export default defaultObject;
