const defaultObject = {
	objectID: 37299,
	isHighlight: false,
	accessionNumber: 'JP1059',
	accessionYear: '1915',
	isPublicDomain: true,
	primaryImage:
		'https://images.metmuseum.org/CRDImages/as/original/DP135567.jpg',
	primaryImageSmall:
		'https://images.metmuseum.org/CRDImages/as/web-large/DP135567.jpg',
	additionalImages: [],
	constituents: [
		{
			constituentID: 11410,
			role: 'Artist',
			name: 'Kitagawa Utamaro',
			constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500054492',
			constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q272045',
			gender: '',
		},
	],
	department: 'Asian Art',
	objectName: 'Print',
	title: 'Shells under Water',
	culture: 'Japan',
	period: 'Edo period (1615–1868)',
	dynasty: '',
	reign: '',
	portfolio: '',
	artistRole: 'Artist',
	artistPrefix: '',
	artistDisplayName: 'Kitagawa Utamaro',
	artistDisplayBio: 'Japanese, ca. 1754–1806',
	artistSuffix: '',
	artistAlphaSort: 'Kitagawa Utamaro',
	artistNationality: 'Japanese',
	artistBeginDate: '1754',
	artistEndDate: '1806',
	artistGender: '',
	artistWikidata_URL: 'https://www.wikidata.org/wiki/Q272045',
	artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500054492',
	objectDate: '1790',
	objectBeginDate: 1790,
	objectEndDate: 1790,
	medium: 'Woodblock print; ink and color on paper',
	dimensions: '9 1/8 x 14 7/8 in. (23.2 x 37.8 cm)',
	measurements: [
		{
			elementName: 'Overall',
			elementDescription: null,
			elementMeasurements: { Height: 23.2, Width: 37.8 },
		},
	],
	creditLine: 'Gift of Estate of Samuel Isham, 1915',
	geographyType: '',
	city: '',
	state: '',
	county: '',
	country: '',
	region: '',
	subregion: '',
	locale: '',
	locus: '',
	excavation: '',
	river: '',
	classification: 'Prints',
	rightsAndReproduction: '',
	linkResource: '',
	metadataDate: '2020-09-16T18:35:19.457Z',
	repository: 'Metropolitan Museum of Art, New York, NY',
	objectURL: 'https://www.metmuseum.org/art/collection/search/37299',
	tags: [
		{
			term: 'Shells',
			AAT_URL: 'http://vocab.getty.edu/page/aat/300011829',
			Wikidata_URL: 'https://www.wikidata.org/wiki/Q213096',
		},
	],
	objectWikidata_URL: '',
	isTimelineWork: false,
	GalleryNumber: '',
};

export default defaultObject;
